### ISSUE TITLE
Dependabot alert for kramdown ruby gem

### ISSUE THREAD

**Issue by carlosmmatos** [ComplianceAsCode/ComplianceAsCode.github.io#6]
I accidentally dismissed this - even though it should still show up. I wanted to put it here to see if this is worth updating, or accepting the risk:

https://github.com/ComplianceAsCode/ComplianceAsCode.github.io/network/alert/Gemfile.lock/kramdown/closed

**Comment by jan-cerny** [comment]
It looks like updating Jekyll would help ... https://github.com/ComplianceAsCode/ComplianceAsCode.github.io/pull/7/commits/3c3867a373b075d1034f082ed232277c9f91a385#diff-e79a60dc6b85309ae70a6ea8261eaf95L24

**Comment by jan-cerny** [comment]
After merging the PRs created by dependabot the alert is no longer visible.
